# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "social-boat"
client_id = "6473dac7576511aadb33abc2ac1d2a53"
application_url = "https://3d46-122-182-155-254.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_script_tags,read_script_tags,write_themes,read_themes"

[auth]
redirect_urls = [
  "https://3d46-122-182-155-254.ngrok-free.app/auth/callback",
  "https://3d46-122-182-155-254.ngrok-free.app/auth/shopify/callback",
  "https://3d46-122-182-155-254.ngrok-free.app/api/auth/callback",
  "https://3d46-122-182-155-254.ngrok-free.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-fecb20e3.myshopify.com"
